### ISSUE TITLE
No such file or directory: textflag.h

### ISSUE THREAD

**Issue by patsys** [paypal/gatt#73] opened 2016-05-12 08:31 UTC
No FIle textflag.h

github.com/paypal/gatt/linux/socket/asm.s:6 6a: No such file or directory: textflag.h

**Comment by afh** [comment] 2016-06-21 17:02
I'm running into the same issue on Debian 8. What is the proposed solution?

**Comment by alloro** [comment] 2016-06-30 14:39
Problem could be fixed by updating go. The problem is fixed for the versions >=1.4

**Comment by afh** [comment] 2016-06-30 15:16
@alloro Thank you. I can confirm that paypal/gatt works with go 1.6.2. I was surprised to find "such an old" version of go (1.3) on the system I was using.

IMHO this issue can be closed.

**Closed as completed** 2017-12-19 16:15 UTC
